# Generated by Django 5.2.17 on 2026-09-26 23:41

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUBMITTED_TO_LPK', 'Diterima LPK'), ('ADMIN_REVIEW', 'Diperiksa admin'), ('CANDIDATE', 'Kandidat'), ('CV_PREPARED', 'CV disiapkan'), ('EXTERNALLY_APPLIED', 'Diajukan oleh LPK'), ('DOCUMENT_SELECTION', 'Seleksi dokumen'), ('INTERVIEW', 'Wawancara'), ('RESERVE', 'Cadangan'), ('PASSED', 'Lulus'), ('FAILED', 'Belum lulus'), ('WITHDRAWN', 'Ditarik'), ('MEDICAL', 'Pemeriksaan kesehatan'), ('DOCUMENT_PROCESS', 'Pengurusan dokumen'), ('DEPARTURE_PROCESS', 'Persiapan keberangkatan'), ('DEPARTED', 'Berangkat')], db_index=True, default='SUBMITTED_TO_LPK', max_length=30)),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Kode lowongan')),
                ('title', models.CharField(max_length=200, verbose_name='Posisi')),
                ('company', models.CharField(max_length=200, verbose_name='Perusahaan')),
                ('program', models.CharField(choices=[('MAGANG', 'Magang'), ('SSW', 'Tokutei Ginou')], max_length=30, verbose_name='Program')),
                ('industry', models.CharField(max_length=100, verbose_name='Bidang')),
                ('prefecture', models.CharField(max_length=100, verbose_name='Prefektur')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lokasi')),
                ('salary', models.CharField(blank=True, max_length=200, verbose_name='Informasi gaji (sertakan mata uang)')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Jadwal kerja')),
                ('overtime', models.CharField(blank=True, max_length=200, verbose_name='Lembur')),
                ('quota', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kuota')),
                ('requirements', models.TextField(blank=True, max_length=5000, verbose_name='Persyaratan')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Usia minimum')),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Usia maksimum')),
                ('min_height', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(250)], verbose_name='Tinggi minimum (cm)')),
                ('japanese_level', models.CharField(blank=True, max_length=80, verbose_name='Sertifikat bahasa yang diperlukan')),
                ('skill', models.CharField(blank=True, max_length=150, verbose_name='Sertifikat keterampilan')),
                ('education', models.CharField(blank=True, max_length=100, verbose_name='Pendidikan')),
                ('experience', models.CharField(blank=True, max_length=300, verbose_name='Pengalaman')),
                ('interview_at', models.DateTimeField(blank=True, null=True, verbose_name='Jadwal wawancara')),
                ('interview_method', models.CharField(blank=True, max_length=200, verbose_name='Metode wawancara')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Batas pengajuan')),
                ('notes', models.TextField(blank=True, max_length=3000, verbose_name='Catatan publik')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Terbuka'), ('CLOSED', 'Ditutup'), ('SELECTION', 'Seleksi'), ('COMPLETED', 'Selesai'), ('ARCHIVED', 'Diarsipkan')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('SUBMITTED_TO_LPK', 'Diterima LPK'), ('ADMIN_REVIEW', 'Diperiksa admin'), ('CANDIDATE', 'Kandidat'), ('CV_PREPARED', 'CV disiapkan'), ('EXTERNALLY_APPLIED', 'Diajukan oleh LPK'), ('DOCUMENT_SELECTION', 'Seleksi dokumen'), ('INTERVIEW', 'Wawancara'), ('RESERVE', 'Cadangan'), ('PASSED', 'Lulus'), ('FAILED', 'Belum lulus'), ('WITHDRAWN', 'Ditarik'), ('MEDICAL', 'Pemeriksaan kesehatan'), ('DOCUMENT_PROCESS', 'Pengurusan dokumen'), ('DEPARTURE_PROCESS', 'Persiapan keberangkatan'), ('DEPARTED', 'Berangkat')], max_length=30)),
                ('note', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.application')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=80)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='cv_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cvversion'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(verbose_name='Tanggal dan waktu')),
                ('location', models.CharField(max_length=400, verbose_name='Lokasi / tautan online')),
                ('notes', models.TextField(blank=True, max_length=2000, verbose_name='Catatan untuk siswa')),
                ('result', models.CharField(choices=[('PENDING', 'Belum ada hasil'), ('PASSED', 'Lulus'), ('FAILED', 'Belum lulus'), ('RESERVE', 'Cadangan'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=50, verbose_name='Hasil')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='core.application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.job'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('url', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Nama lengkap')),
                ('name_kana', models.CharField(blank=True, max_length=150, verbose_name='Nama katakana')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Pria'), ('F', 'Wanita')], max_length=10, verbose_name='Jenis kelamin')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Tanggal lahir')),
                ('birth_place', models.CharField(blank=True, max_length=150, verbose_name='Tempat lahir')),
                ('address', models.TextField(blank=True, max_length=1000, verbose_name='Alamat lengkap')),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu'), ('Lainnya', 'Lainnya'), ('Tidak menyatakan', 'Tidak menyatakan')], max_length=40, verbose_name='Agama')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Nomor telepon')),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Belum menikah'), ('MARRIED', 'Menikah'), ('DIVORCED', 'Cerai')], max_length=20, verbose_name='Status pernikahan')),
                ('health', models.CharField(blank=True, max_length=300, verbose_name='Kondisi kesehatan')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('Belum tahu', 'Belum tahu')], max_length=10, verbose_name='Golongan darah')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name='Tinggi badan (cm)')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)], verbose_name='Berat badan (kg)')),
                ('smoking', models.BooleanField(blank=True, null=True, verbose_name='Merokok')),
                ('alcohol', models.BooleanField(blank=True, null=True, verbose_name='Mengonsumsi alkohol')),
                ('tattoo', models.BooleanField(blank=True, null=True, verbose_name='Memiliki tato')),
                ('passport', models.BooleanField(blank=True, null=True, verbose_name='Memiliki paspor')),
                ('study_months', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(600)], verbose_name='Lama belajar bahasa Jepang (bulan)')),
                ('japanese_certificate', models.CharField(blank=True, choices=[('Tidak ada', 'Tidak ada'), ('JFT BASIC A2', 'JFT BASIC A2'), ('JLPT N5', 'JLPT N5'), ('JLPT N4', 'JLPT N4'), ('JLPT N3', 'JLPT N3'), ('JLPT N2', 'JLPT N2'), ('JLPT N1', 'JLPT N1'), ('Lainnya', 'Lainnya')], max_length=25, verbose_name='Sertifikat bahasa Jepang')),
                ('strengths', models.TextField(blank=True, max_length=1000, verbose_name='Kelebihan')),
                ('weaknesses', models.TextField(blank=True, max_length=1000, verbose_name='Kekurangan')),
                ('hobbies', models.TextField(blank=True, max_length=1000, verbose_name='Hobi')),
                ('home_phone', models.CharField(blank=True, max_length=25, verbose_name='Telepon rumah (opsional)')),
                ('eyesight', models.CharField(blank=True, max_length=100, verbose_name='Penglihatan (opsional)')),
                ('dominant_hand', models.CharField(blank=True, choices=[('RIGHT', 'Kanan'), ('LEFT', 'Kiri'), ('BOTH', 'Keduanya')], max_length=10, verbose_name='Tangan dominan')),
                ('english_level', models.CharField(blank=True, max_length=100, verbose_name='Kemampuan bahasa Inggris')),
                ('other_languages', models.CharField(blank=True, max_length=150, verbose_name='Bahasa lain')),
                ('favorite_subject', models.CharField(blank=True, max_length=150, verbose_name='Pelajaran favorit')),
                ('aspirations', models.TextField(blank=True, max_length=1000, verbose_name='Harapan gaji, bidang, durasi, lokasi (opsional)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('UNDER_REVIEW', 'Dalam pemeriksaan'), ('NEEDS_REVISION', 'Perlu revisi'), ('VERIFIED', 'Terverifikasi'), ('REVERIFICATION_REQUIRED', 'Perlu verifikasi ulang')], db_index=True, default='DRAFT', max_length=30)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('review_note', models.TextField(blank=True, max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JapanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200, verbose_name='Perusahaan Jepang')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Kumiai / organisasi')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Kontak perusahaan / penanggung jawab')),
                ('address', models.TextField(blank=True, max_length=500, verbose_name='Alamat perusahaan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japan_history', to='core.studentprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Nama keluarga')),
                ('relationship', models.CharField(max_length=80, verbose_name='Hubungan')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Umur')),
                ('occupation', models.CharField(blank=True, max_length=150, verbose_name='Pekerjaan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='core.studentprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Mulai sekolah')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Lulus / selesai')),
                ('level', models.CharField(choices=[('SD', 'SD'), ('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK'), ('Diploma', 'Diploma'), ('Sarjana', 'Sarjana'), ('Lainnya', 'Lainnya')], max_length=25, verbose_name='Jenjang')),
                ('institution', models.CharField(max_length=200, verbose_name='Nama sekolah')),
                ('major', models.CharField(blank=True, max_length=150, verbose_name='Jurusan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.studentprofile')),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('KTP', 'KTP'), ('KK', 'Kartu Keluarga'), ('BIRTH', 'Akta kelahiran'), ('EDUCATION', 'Ijazah'), ('HEALTH', 'Dokumen kesehatan'), ('CONSENT', 'Surat izin keluarga'), ('PHOTO', 'Pas foto'), ('PASSPORT', 'Paspor (jika ada)'), ('LANGUAGE', 'Sertifikat bahasa Jepang'), ('SKILL', 'Sertifikat SSW'), ('OTHER', 'Dokumen lain')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Keterangan (misalnya Ijazah SD)')),
                ('file', models.FileField(upload_to=core.models.private_path)),
                ('original_name', models.CharField(max_length=250)),
                ('size', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Diunggah'), ('UNDER_REVIEW', 'Diperiksa'), ('VERIFIED', 'Terverifikasi'), ('NEEDS_REVISION', 'Perlu revisi')], default='UPLOADED', max_length=20)),
                ('is_current', models.BooleanField(default=True)),
                ('review_note', models.TextField(blank=True, max_length=2000)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.document')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cvversion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.studentprofile'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Tanggal diterbitkan')),
                ('name', models.CharField(max_length=250, verbose_name='Nama sertifikat / ijazah')),
                ('kind', models.CharField(choices=[('LANGUAGE', 'Bahasa'), ('SKILL', 'SSW / keterampilan'), ('OTHER', 'Lainnya')], max_length=15, verbose_name='Jenis')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.studentprofile')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.studentprofile'),
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=3000, verbose_name='Catatan')),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal admin'), ('STUDENT', 'Terlihat siswa')], default='INTERNAL', max_length=20, verbose_name='Visibilitas')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='core.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Mulai kerja')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Selesai kerja')),
                ('company', models.CharField(max_length=200, verbose_name='Nama perusahaan')),
                ('industry', models.CharField(blank=True, max_length=150, verbose_name='Bidang industri')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Deskripsi pekerjaan')),
                ('leaving_reason', models.CharField(blank=True, max_length=300, verbose_name='Alasan berhenti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='core.studentprofile')),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cvversion',
            constraint=models.UniqueConstraint(fields=('student', 'number'), name='unique_cv_version'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'job'), name='unique_student_job'),
        ),
    ]
